# Generated by Django 3.1.4 on 2020-12-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(upload_to='foto', verbose_name='Imagem'),
        ),
    ]
