# Generated by Django 3.1.4 on 2020-12-23 19:38

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20201222_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='foto', verbose_name='Imagem'),
        ),
    ]
