# Generated by Django 3.1.4 on 2020-12-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_auto_20201223_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(upload_to='foto/%Y/%m/%d'),
        ),
    ]
